ARG TARGETPLATFORM
ARG FROMPLATFORM=${TARGETPLATFORM}
ARG FROMIMAGE
FROM --platform=${FROMPLATFORM} ${FROMIMAGE}

RUN \
  cd pytorch && \
  git apply --check ../arm.patch || : && \
  timeout --preserve-status --kill-after=330m --verbose 300m python setup.py || :
